export { default as Home } from "./Home";
export { default as Auth } from "./Auth";
export { default as CreateMemory } from "./CreateMemory";
export { default as Login } from "./Login";
export { default as Registration } from "./Registration";
export { default as Defaultpage } from "./Defaultpage";
export { default as NotFoundPage } from "./NotFoundPage";
export { default as Removal } from "./Removal";
export { default as ForgotPassword } from "./ForgotPassword";
